Add Endpoint for SCP: SL Server and simple scplist.kr impl (unused) also cleanup because 400+ lines files scare me
AlexInABox/zeitvertreib-discord pull request #3
Opened 2024-08-02 17:26 UTC by RadSton

- Added package-lock.json to .gitignore
- Added my backend DataTransmitServer (Mod: https://github.com/RadSton/DataTransmitter) 
- Added express@4.19.2
- Added simple SCPListKr-API impl. (currently unused)
- Removed CEDMODE_BASE_URL enviroment variable (unused)
- Moved sendPowerEventToServer, reinstallServer, isServerInstalling to extra Peterodactyl.js file
- Simplified registering Bot commands with BotCommands.js (just do BotCommands.registerCommand("command", (interaction) => { // HANDLE IT //});
- Moved Discord Command registration to extra file in root directory
- Added the discord command registration to "npm install" so it runs after the module install
-  Moved CedMod function to another file (unused)
- Removed CedMod player counter
- Implemented DataTransmitServer callbacks and playerCount

2024-08-02 20:09 UTC, AlexInABox requested changes
Let's just hardcode the port that will be opened for the playerList listener. When modifying the .env port, the dockerfile must also be adjusted to expose this specific port.

2024-08-02 20:09 UTC, AlexInABox commented on lib/SCPListKr.js
> +const stopGettingInfo = () => {
Can you not just use clearInterval once without modifying intervalID anymore?

2024-08-02 20:09 UTC, AlexInABox commented on lib/SCPListKr.js
> +    if (intervalId < 0) return;
So this compares an Interval with a number?

2024-08-02 20:20 UTC, RadSton commented on lib/SCPListKr.js
> +    if (intervalId < 0) return;
This is my mistake I did not know until now that the NodeJS implementation of intervals work differently than the implementation from browsers. In a browser setInterval returns an intervalId as Number but in NodeJS it returns an object. The more you know! But I will remove the checks since clearInterval doesnt error in any scenario

2024-08-02 20:28 UTC, RadSton commented on .gitignore
> +package-lock.json
https://github.com/AlexInABox/zeitvertreib-discord/pull/3/commits/66a9d10f827548cd41cb144c625d4673711eeeac#diff-bc37d034bad564583790a46f19d807abfe519c5671395fd494d8cce506c42947L131

2024-08-02 20:29 UTC, RadSton commented on index.js
> +let Players = [];
https://github.com/AlexInABox/zeitvertreib-discord/pull/3/commits/66a9d10f827548cd41cb144c625d4673711eeeac#diff-e727e4bdf3657fd1d798edcd6b099d6e092f8573cba266154583a746bba0f346L22-L23

2024-08-02 20:29 UTC, RadSton commented on lib/Pterodactyl.js
> +        return isInstalling === true;
https://github.com/AlexInABox/zeitvertreib-discord/pull/3/commits/66a9d10f827548cd41cb144c625d4673711eeeac#diff-12ad68b15e2c3fb3ae6e0615df82b6a33e51a010f90e529365bb141594d5b850L59

2024-08-02 20:29 UTC, RadSton commented on lib/SCPListKr.js
> +    if (intervalId < 0) return;
https://github.com/AlexInABox/zeitvertreib-discord/pull/3/commits/66a9d10f827548cd41cb144c625d4673711eeeac#diff-11a72c602e63fa60386308c61a90867d7bb27c7fa4d1003872161dd587bb39baL35

2024-08-02 20:45 UTC, RadSton commented
> Let's just hardcode the port that will be opened for the playerList listener. When modifying the .env port, the dockerfile must also be adjusted to expose this specific port.

Port 80 is now hard coded at
https://github.com/AlexInABox/zeitvertreib-discord/pull/3/commits/66a9d10f827548cd41cb144c625d4673711eeeac#diff-e727e4bdf3657fd1d798edcd6b099d6e092f8573cba266154583a746bba0f346L36-R35
and exposed it in Dockerfile since this is the port you sent me yesterday

https://github.com/AlexInABox/zeitvertreib-discord/pull/3/commits/0b587711c6f2adcb54f429c3d0d593f8054a3ca6

2024-08-03 08:40 UTC, AlexInABox approved these changes
Yipie

2024-08-03 08:40 UTC, merged